[package]
name = "override-operator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = {version="0.3", features=["std", "registry", "env-filter"]}
kube = { version = "0.75", features = ["client", "runtime", "derive"] }
k8s-openapi = { version = "0.16", features = ["v1_25"] }
tokio = { version = "1.21", features = ["full"] }
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
schemars = { version = "0.8" }
maplit = "1.0"
