---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: override-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: override-operator
  labels:
    app: override-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: override-operator
  template:
    metadata:
      labels:
        app: override-operator
    spec:
      serviceAccountName: override-operator
      containers:
      - name: override-operator
        image: docker.io/mtinside/override-operator:0.0.3
        imagePullPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: override-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["networking.istio.io"]
    resources: ["destinationrules", "virtualservices"] # MUST be all lower and plural. NOT validated at apply.
    verbs: ["create", "patch", "update", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: override-operator
subjects:
  - kind: ServiceAccount
    name: override-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: override-operator
